### ISSUE TITLE
Add a way for paths to be flipped and moved

### ISSUE THREAD

**Issue by SilentWanderer** [wpilibsuite/PathUI#44]
One usability issue I've run into while using other path planners is that paths often have to be reflected along the X or Y axis in order to accommodate autonomous routines that start in different positions.

Preferably, this would be implemented as buttons to "flip" a path horizontally and vertically. Translations would be achieved through the use of X and Y fields that indicate the coordinates of the path and shift the whole path if changed.

**Comment by gftabor** [comment]
I like this idea. Probably should also start with a way to duplicate an existing path. On first pass I would think 

a duplicate method added to MainIOUtil that duplicates a file. From there a flip about line function in Path. And next to the  add/remove buttons on the path menu in MainController add a flip horizontally and a flip vertically button.

**Comment by gftabor** [comment]
Fixed with #53 and #48
